### ISSUE TITLE
Create domain mapping for prod and staging

### ISSUE THREAD

**Issue by KevinDyer** [graffiticode/L102#4]
The [prod](https://console.cloud.google.com/run/detail/us-central1/l102/metrics?cloudshell=false&project=graffiticode) and [staging](https://console.cloud.google.com/run/detail/us-central1/l102/metrics?cloudshell=false&project=graffiticode) instances are ready a gc.artcompiler.com domain mapping

**Comment by jeffdyer** [comment]
Done.
